version: '3'

services:
  db:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: rootpass
      MARIADB_USER: lab5-backend
      MARIADB_PASSWORD: changeme
      MARIADB_DATABASE: lab5
    networks:
      - backend
    volumes:
      - lab5:/var/lib/mysql

  backend:
    build: ./backend
    depends_on:
      - db
    ports:
      - 8000:8000
    networks:
      - backend
      - frontend

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - 8080:80
    networks:
      - frontend

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8888:80
    depends_on:
      - db
    environment:
      PMA_HOST: db
    networks:
      - backend

networks:
  backend: {}
  frontend: {}

volumes:
  lab5:
